# Non-sensitive environment variables for the backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-config
  labels:
    app: ai-api-gateway
data:
  VISION_MODEL_URL: "PLACEHOLDER"
  TRANSLATE_MODEL_URL: "PLACEHOLDER"
  LOGIC_MODEL_URL: "PLACEHOLDER"
  TTS_API_URL: "PLACEHOLDER"
  HOME_ASSISTANT_URL: "PLACEHOLDER"
  PERSON_ID_SERVICE_URL: "http://person-id-svc:8100"
