"""Consolidated baseline schema for cognitive-companion.

Squash of the former 22-migration chain (0001_baseline .. 0020_activity_session_source)
into the final state only. Objects that earlier migrations created and later ones
dropped are not created here at all: pipeline step branch columns, the
emergency_alerts table, the legacy location tables (person_location_history,
room_presence_intervals), the pipeline_edges (source_step_id, source_port) unique
constraint, and cts_window step-config keys.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-27

"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

import backend.core.time
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# location_observations is a TimescaleDB hypertable partitioned on observed_at.
_CREATE_HYPERTABLE = (
    "SELECT create_hypertable('location_observations', 'observed_at', "
    "chunk_time_interval => INTERVAL '6 hours', if_not_exists => TRUE)"
)

# Continuous aggregate backing the spatial density heatmaps.
_CREATE_CAGG = """
CREATE MATERIALIZED VIEW location_heatmaps_15m
WITH (timescaledb.continuous) AS
SELECT
    person_id,
    time_bucket('15 minutes', observed_at) AS time_bucket_15m,
    floor(floor_x_m / 0.5) * 0.5 AS x_bin,
    floor(floor_y_m / 0.5) * 0.5 AS y_bin,
    count(*) AS weight
FROM location_observations
WHERE floor_x_m IS NOT NULL AND floor_y_m IS NOT NULL
GROUP BY 1, 2, 3, 4
WITH NO DATA
"""

_ADD_CAGG_POLICY = """
SELECT add_continuous_aggregate_policy('location_heatmaps_15m',
    start_offset => INTERVAL '3 days',
    end_offset   => INTERVAL '15 minutes',
    schedule_interval => INTERVAL '15 minutes')
"""


def upgrade() -> None:
    """Upgrade schema."""
    # -- Extensions -----------------------------------------------------------
    # The shared db/ init script installs these too; repeated here so a bare
    # database can be brought up from this migration alone.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('expression', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'::character varying"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cts_camera_overlap_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('camera_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cts_dementia_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('person_id', sa.String(length=255), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('window_start', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('window_end', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('algorithm_version', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('feedback', sa.String(length=16), nullable=True),
    sa.Column('evidence_grade', sa.String(length=32), nullable=True),
    sa.Column('superseded_by_revision_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cts_dementia_signals_person_id'), 'cts_dementia_signals', ['person_id'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_severity'), 'cts_dementia_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_signal_id'), 'cts_dementia_signals', ['signal_id'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_signal_type'), 'cts_dementia_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_superseded_by_revision_id'), 'cts_dementia_signals', ['superseded_by_revision_id'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_window_end'), 'cts_dementia_signals', ['window_end'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_window_start'), 'cts_dementia_signals', ['window_start'], unique=False)
    op.create_table('cts_identity_revision_log',
    sa.Column('revision_id', sa.String(length=128), nullable=False),
    sa.Column('ph_id', sa.String(length=128), nullable=False),
    sa.Column('previous_identity_id', sa.String(length=128), nullable=True),
    sa.Column('new_identity_id', sa.String(length=128), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('applied_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('rewritten_rows', sa.Integer(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index('ix_cts_identity_revision_log_applied_at', 'cts_identity_revision_log', [sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('ix_cts_identity_revision_log_kind_applied', 'cts_identity_revision_log', ['kind', sa.literal_column('applied_at DESC')], unique=False)
    op.create_index('ix_cts_identity_revision_log_ph_applied', 'cts_identity_revision_log', ['ph_id', sa.literal_column('applied_at DESC')], unique=False)
    op.create_table('cts_window_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('window_seconds', sa.Float(), server_default=sa.text("'10'::double precision"), nullable=False),
    sa.Column('min_detections', sa.Integer(), server_default=sa.text("1"), nullable=False),
    sa.Column('min_identities', sa.Integer(), server_default=sa.text("1"), nullable=False),
    sa.Column('cameras', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rooms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cooldown_seconds', sa.Float(), server_default=sa.text("'0'::double precision"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=256), nullable=True),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('media_paths_json', sa.JSON(), nullable=True),
    sa.Column('pipeline_data_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow_execution_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_rule_name'), 'event_logs', ['rule_name'], unique=False)
    op.create_index('ix_event_logs_rule_status_ts', 'event_logs', ['rule_id', 'status', 'timestamp'], unique=False)
    op.create_index(op.f('ix_event_logs_status'), 'event_logs', ['status'], unique=False)
    op.create_index(op.f('ix_event_logs_timestamp'), 'event_logs', ['timestamp'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('alert_priority', sa.Integer(), server_default=sa.text("5"), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('cts_alert_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_settings',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('floor_plan_key', sa.String(length=512), nullable=True),
    sa.Column('floor_plan_width', sa.Integer(), nullable=True),
    sa.Column('floor_plan_height', sa.Integer(), nullable=True),
    sa.Column('floor_meters_per_pixel', sa.Float(), nullable=True),
    sa.Column('cts_adjacency_edges', sa.JSON(), nullable=True),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_household_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('font_filename', sa.String(length=256), nullable=False),
    sa.Column('regions_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_templates_name'), 'image_templates', ['name'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='uploaded', nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('uploaded','chunked','approved','archived')", name='ck_knowledge_documents_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_documents_status', 'knowledge_documents', ['status'], unique=False)
    op.create_table('media_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('presigned_url', sa.Text(), nullable=True),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('captured_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_cache_captured_at'), 'media_cache', ['captured_at'], unique=False)
    op.create_index(op.f('ix_media_cache_expires_at'), 'media_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_media_cache_object_name'), 'media_cache', ['object_name'], unique=True)
    op.create_index(op.f('ix_media_cache_sensor_id'), 'media_cache', ['sensor_id'], unique=False)
    op.create_table('room_occupancy_state',
    sa.Column('room_name', sa.String(length=128), nullable=False),
    sa.Column('occupied', sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column('since', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'unknown'::character varying"), nullable=False),
    sa.Column('person_ids', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('last_updated', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('room_name')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ha_area_id', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('floor_polygon', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_camera', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('inferred_dwell_alert_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[\"sensor_event\"]'::jsonb"), nullable=False),
    sa.Column('primary_sensor_id', sa.String(length=128), nullable=True),
    sa.Column('webhook_config', sa.JSON(), nullable=True),
    sa.Column('occupancy_config', sa.JSON(), nullable=True),
    sa.Column('telegram_trigger_config', sa.JSON(), nullable=True),
    sa.Column('cool_off_minutes', sa.Integer(), nullable=False),
    sa.Column('max_daily_triggers', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_executions', sa.Integer(), nullable=False),
    sa.Column('execution_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=True)
    op.create_table('senior_knowledge_queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asked_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('senior_id', sa.Text(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), server_default='', nullable=False),
    sa.Column('source_document_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('source_chunk_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('top_similarity', sa.Float(), nullable=True),
    sa.Column('answered_via', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_senior_kq_asked_at', 'senior_knowledge_queries', ['asked_at'], unique=False, postgresql_using='btree')
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('event_log_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_data_json', sa.JSON(), nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resume_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_log_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_rule_id'), 'workflow_executions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_table('active_image_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('expires_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_served_hash', sa.String(length=64), nullable=True),
    sa.Column('last_served_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['image_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_image_state_sensor_id'), 'active_image_state', ['sensor_id'], unique=True)
    op.create_table('activity_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('opened_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('closed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('open_event_id', sa.Integer(), nullable=True),
    sa.Column('close_event_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='vision_inferred', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['close_event_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['open_event_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_sessions_activity_type'), 'activity_sessions', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_sessions_observation_id'), 'activity_sessions', ['observation_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_opened_at'), 'activity_sessions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_activity_sessions_person_id'), 'activity_sessions', ['person_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_source'), 'activity_sessions', ['source'], unique=False)
    op.create_table('companion_surfaces',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('surface_type', sa.String(length=16), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_source', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('room_mismatch', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_surfaces_room_id'), 'companion_surfaces', ['room_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cts_alert_suppressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('signal_kind', sa.String(length=64), nullable=True),
    sa.Column('suppressed_until', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_suppressions_person_until', 'cts_alert_suppressions', ['person_id', 'suppressed_until'], unique=False)
    op.create_table('cts_cameras',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rtsp_url', sa.String(length=1024), nullable=False),
    sa.Column('room_name', sa.String(length=256), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rotation_degrees', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('face_id_enabled', sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column('face_id_min_confidence', sa.Float(), nullable=True),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'surveillance'::character varying"), nullable=False),
    sa.Column('horizontal_fov_deg', sa.Float(), nullable=True),
    sa.Column('mounting_height_m', sa.Float(), nullable=True),
    sa.Column('tilt_deg', sa.Float(), nullable=True),
    sa.Column('snapshot_width', sa.Integer(), nullable=True),
    sa.Column('snapshot_height', sa.Integer(), nullable=True),
    sa.Column('floor_plan_key', sa.String(length=512), nullable=True),
    sa.Column('homography', sa.JSON(), nullable=True),
    sa.Column('homography_residuals', sa.JSON(), nullable=True),
    sa.Column('homography_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('homography_residual_m', sa.Float(), nullable=True),
    sa.Column('homography_method', sa.String(length=32), nullable=True),
    sa.Column('homography_set_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('frame_natural_width', sa.Integer(), nullable=True),
    sa.Column('frame_natural_height', sa.Integer(), nullable=True),
    sa.Column('visibility_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('marker_x_norm', sa.Float(), nullable=True),
    sa.Column('marker_y_norm', sa.Float(), nullable=True),
    sa.Column('marker_heading_deg', sa.Float(), nullable=True),
    sa.Column('marker_set_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('privacy_zones', sa.JSON(), nullable=True),
    sa.Column('floor_region_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('floor_region_source', sa.String(length=16), nullable=True),
    sa.Column('floor_region_set_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('needs_recalibration', sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column('drift_checked_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('drift_reason', sa.Text(), nullable=True),
    sa.Column('calibration_ref_key', sa.String(length=512), nullable=True),
    sa.Column('health_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_cts_cameras_room_id', ),
    sa.CheckConstraint('rotation_degrees IN (0, 90, 180, 270)', name='ck_cts_cameras_rotation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cts_cameras_name'), 'cts_cameras', ['name'], unique=False)
    op.create_index(op.f('ix_cts_cameras_room_id'), 'cts_cameras', ['room_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sleep_total_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('sleep_disruptions', sa.Integer(), nullable=True),
    sa.Column('meal_prep_count', sa.Integer(), nullable=True),
    sa.Column('meal_eating_count', sa.Integer(), nullable=True),
    sa.Column('meal_avg_duration_minutes', sa.Float(), nullable=True),
    sa.Column('medication_doses_taken', sa.Integer(), nullable=True),
    sa.Column('medication_doses_due', sa.Integer(), nullable=True),
    sa.Column('medication_adherence_pct', sa.Float(), nullable=True),
    sa.Column('bathroom_visit_count', sa.Integer(), nullable=True),
    sa.Column('bathroom_total_minutes', sa.Integer(), nullable=True),
    sa.Column('bathroom_avg_duration_minutes', sa.Float(), nullable=True),
    sa.Column('door_open_count', sa.Integer(), nullable=True),
    sa.Column('door_close_count', sa.Integer(), nullable=True),
    sa.Column('exercise_session_count', sa.Integer(), nullable=True),
    sa.Column('exercise_total_minutes', sa.Integer(), nullable=True),
    sa.Column('room_time_json', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.String(length=4096), nullable=True),
    sa.Column('summary_created_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('wellness_score', sa.Float(), nullable=True),
    sa.Column('wellness_alerts_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'report_date', name='uix_person_date')
    )
    op.create_index(op.f('ix_daily_reports_person_id'), 'daily_reports', ['person_id'], unique=False)
    op.create_table('info_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('layout_id', sa.Text(), server_default='text_only', nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('voice_instruction', sa.Text(), server_default='', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','caregiver_review','approved','archived')", name='ck_info_cards_status'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_kdc_doc_chunk')
    )
    op.create_index('idx_kdc_embedding', 'knowledge_document_chunks', ['embedding'], unique=False, postgresql_using='diskann', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('knowledge_document_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('minio_object_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.Text(), server_default='', nullable=False),
    sa.Column('ord', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('floor_x_m', sa.Float(), nullable=True),
    sa.Column('floor_y_m', sa.Float(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text("'0.5'::double precision"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id', 'observed_at', name='location_observations_pkey')
    )
    op.create_index('idx_loc_obs_person', 'location_observations', ['person_id', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index('idx_loc_obs_room', 'location_observations', ['room_id', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index('location_observations_observed_at_idx', 'location_observations', [sa.literal_column('observed_at DESC')], unique=False)
    # Convert to a hypertable after the observed_at index exists, so TimescaleDB
    # reuses it instead of creating its own duplicate default time index.
    op.execute(_CREATE_HYPERTABLE)
    op.create_table('person_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('detected_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['event_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_activities_activity_type'), 'person_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_person_activities_detected_at'), 'person_activities', ['detected_at'], unique=False)
    op.create_index(op.f('ix_person_activities_observation_id'), 'person_activities', ['observation_id'], unique=False)
    op.create_index(op.f('ix_person_activities_person_id'), 'person_activities', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_activities_session_id'), 'person_activities', ['session_id'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), server_default='', nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position_x', sa.Float(), server_default='0', nullable=False),
    sa.Column('position_y', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_rule_id'), 'pipeline_steps', ['rule_id'], unique=False)
    op.create_table('presence_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('exited_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('entry_source', sa.String(length=32), nullable=False),
    sa.Column('exit_source', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text("'0.5'::double precision"), nullable=False),
    sa.Column('quality', sa.Float(), server_default=sa.text("'0'::double precision"), nullable=False),
    sa.Column('last_observed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('backfill_revision_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['presence_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ps_person_open', 'presence_segments', ['person_id'], unique=False, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_index('idx_ps_person_time', 'presence_segments', ['person_id', sa.literal_column('entered_at DESC')], unique=False)
    op.create_index('idx_ps_room_time', 'presence_segments', ['room_id', sa.literal_column('entered_at DESC')], unique=False)
    op.create_index('idx_ps_superseded_by', 'presence_segments', ['superseded_by'], unique=False, postgresql_where=sa.text('superseded_by IS NOT NULL'))
    op.create_index('uq_ps_backfill_revision_entered', 'presence_segments', ['backfill_revision_id', 'entered_at'], unique=True, postgresql_where=sa.text('backfill_revision_id IS NOT NULL'))
    op.create_table('quizzes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('question_layout_id', sa.Text(), server_default='quiz_with_optional_image', nullable=False),
    sa.Column('intro_voice_template', sa.Text(), server_default='', nullable=False),
    sa.Column('voice_instruction', sa.Text(), server_default='', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','caregiver_review','approved','archived')", name='ck_quizzes_status'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('camera_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'name', name='uq_room_zone_name')
    )
    op.create_index(op.f('ix_room_zones_room_id'), 'room_zones', ['room_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('language_override', sa.String(length=16), nullable=True),
    sa.Column('voice_override', sa.String(length=64), nullable=True),
    sa.Column('system_instruction_override', sa.Text(), nullable=True),
    sa.Column('step_timeout_s_override', sa.Integer(), nullable=True),
    sa.Column('max_step_attempts_override', sa.Integer(), nullable=True),
    sa.Column('resume_grace_s_override', sa.Integer(), nullable=True),
    sa.Column('escalation_channels_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summon_channels_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rephrase_via_override', sa.String(length=16), nullable=True),
    sa.Column('activity_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_person_id'), 'routines', ['person_id'], unique=False)
    op.create_table('rule_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('negate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_cron_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('cron_trigger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cron_trigger_id'], ['cron_triggers.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_cron_triggers_cron_trigger_id', 'rule_cron_triggers', ['cron_trigger_id'], unique=False)
    op.create_index('ix_rule_cron_triggers_rule_id', 'rule_cron_triggers', ['rule_id'], unique=False)
    op.create_table('rule_cts_window_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('cts_window_trigger_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cts_window_trigger_id'], ['cts_window_triggers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_cts_window_triggers_ct_id', 'rule_cts_window_triggers', ['cts_window_trigger_id'], unique=False)
    op.create_index('ix_rule_cts_window_triggers_rule_id', 'rule_cts_window_triggers', ['rule_id'], unique=False)
    op.create_table('rule_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependent_rule_id', sa.Integer(), nullable=False),
    sa.Column('parent_rule_id', sa.Integer(), nullable=False),
    sa.Column('lookback_minutes', sa.Integer(), nullable=False),
    sa.Column('require_success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dependent_rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ha_entity_id', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_name'), 'sensors', ['name'], unique=False)
    op.create_table('transit_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), server_default='door', nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inside_room_id', sa.Integer(), nullable=False),
    sa.Column('outside_room_id', sa.Integer(), nullable=False),
    sa.Column('direction_vec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inside_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['outside_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guided_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('surface_id', sa.String(length=128), nullable=True),
    sa.Column('conversation_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step_ord', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('last_activity_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('completed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], name='fk_guided_sessions_conversation_session_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guided_sessions_conversation_session_id'), 'guided_sessions', ['conversation_session_id'], unique=False)
    op.create_index(op.f('ix_guided_sessions_execution_id'), 'guided_sessions', ['execution_id'], unique=False)
    op.create_index('ix_guided_sessions_live_person', 'guided_sessions', ['person_id'], unique=False, postgresql_where=sa.text("status IN ('active', 'waiting', 'summoning', 'escalated', 'caregiver_takeover')"))
    op.create_index(op.f('ix_guided_sessions_person_id'), 'guided_sessions', ['person_id'], unique=False)
    op.create_index(op.f('ix_guided_sessions_routine_id'), 'guided_sessions', ['routine_id'], unique=False)
    op.create_index(op.f('ix_guided_sessions_status'), 'guided_sessions', ['status'], unique=False)
    op.create_index('uq_guided_sessions_one_live_per_person', 'guided_sessions', ['person_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'active', 'waiting', 'summoning', 'escalated', 'caregiver_takeover')"))
    op.create_table('info_card_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('info_card_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('execution_id', sa.BigInteger(), nullable=True),
    sa.Column('channels', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('delivered_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('dismissed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('dismissed_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['info_card_id'], ['info_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_info_deliveries_at', 'info_card_deliveries', ['delivered_at'], unique=False)
    op.create_table('info_card_image_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('info_card_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('source_image_id', sa.BigInteger(), nullable=True),
    sa.Column('original_object_name', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), server_default='', nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['info_card_id'], ['info_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['knowledge_document_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_card_id', 'slot_index', name='uq_icis_card_slot')
    )
    op.create_table('interactive_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('raw_response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactive_responses_created_at'), 'interactive_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactive_responses_execution_id'), 'interactive_responses', ['execution_id'], unique=False)
    op.create_index('ix_interactive_responses_execution_step', 'interactive_responses', ['execution_id', 'step_id'], unique=True)
    op.create_index(op.f('ix_interactive_responses_step_id'), 'interactive_responses', ['step_id'], unique=False)
    op.create_table('pipeline_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('source_step_id', sa.Integer(), nullable=False),
    sa.Column('source_port', sa.String(length=64), nullable=False),
    sa.Column('target_step_id', sa.Integer(), nullable=False),
    sa.Column('target_port', sa.String(length=64), server_default='main', nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_step_id'], ['pipeline_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_step_id'], ['pipeline_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_edges_rule_id'), 'pipeline_edges', ['rule_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('expected_answer', sa.Text(), server_default='', nullable=False),
    sa.Column('explanation', sa.Text(), server_default='', nullable=False),
    sa.Column('image_slot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.CheckConstraint("question_type IN ('multiple_choice', 'open_ended')", name='ck_quiz_questions_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'ord', name='uq_qq_quiz_ord')
    )
    op.create_table('quiz_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('execution_id', sa.BigInteger(), nullable=True),
    sa.Column('senior_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='started', nullable=False),
    sa.Column('current_question_ord', sa.Integer(), server_default='0', nullable=False),
    sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('started','in_progress','completed','abandoned','timed_out')", name='ck_quiz_sessions_status'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_sessions_started_at', 'quiz_sessions', ['started_at'], unique=False)
    op.create_table('routine_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('completion_gate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skip_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('min_duration_s', sa.Integer(), nullable=True),
    sa.Column('step_timeout_s_override', sa.Integer(), nullable=True),
    sa.Column('max_step_attempts_override', sa.Integer(), nullable=True),
    sa.Column('is_safety_critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['room_zones.id'], name='fk_routine_steps_zone_id_room_zones', ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'ord', name='uq_routine_step_ord')
    )
    op.create_index(op.f('ix_routine_steps_routine_id'), 'routine_steps', ['routine_id'], unique=False)
    op.create_table('guided_session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('step_ord', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=24), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['guided_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guided_session_events_at'), 'guided_session_events', ['at'], unique=False)
    op.create_index(op.f('ix_guided_session_events_session_id'), 'guided_session_events', ['session_id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_ord', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('chosen_choice_id', sa.Text(), nullable=True),
    sa.Column('chosen_choice_text', sa.Text(), nullable=True),
    sa.Column('open_ended_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('answered_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_qr_session_question')
    )
    # ### end Alembic commands ###

    # -- Deferred foreign keys ------------------------------------------------
    # event_logs and workflow_executions reference each other, so the cycle
    # cannot be expressed inline. These three are added once every table exists;
    # the names match what Postgres assigned under the original chain.
    op.create_foreign_key(
        'event_logs_rule_id_fkey', 'event_logs', 'rules', ['rule_id'], ['id']
    )
    op.create_foreign_key(
        'event_logs_workflow_execution_id_fkey',
        'event_logs', 'workflow_executions', ['workflow_execution_id'], ['id'],
    )
    op.create_foreign_key(
        'workflow_executions_current_step_id_fkey',
        'workflow_executions', 'pipeline_steps', ['current_step_id'], ['id'],
    )

    # -- Continuous aggregate -------------------------------------------------
    # Depends on location_observations being a hypertable, so it must follow the
    # create_hypertable call above.
    op.execute(sa.text(_CREATE_CAGG))
    op.execute(sa.text(_ADD_CAGG_POLICY))

    # -- Seed data: info_card image template ----------------------------------
    op.execute(
        sa.text(
            """INSERT INTO image_templates (name, description, width, height, image_filename, font_filename, regions_json, is_default)
               VALUES (
                   'info_card',
                   'Info card display (title + image + body)',
                   800, 480,
                   'info_card_bg.png',
                   'NotoSansTamil-Regular.ttf',
                   :regions,
                   false
               )"""
        ).bindparams(
            sa.bindparam(
                "regions",
                value=[
                    {
                        "name": "title",
                        "x": 20,
                        "y": 10,
                        "width": 760,
                        "height": 50,
                        "font_size_max": 28,
                        "font_size_min": 14,
                        "align": "center",
                        "bg_color": [0, 0, 0, 160],
                        "text_color": [255, 255, 255, 255],
                        "multiline": True,
                    },
                    {
                        "name": "image",
                        "x": 20,
                        "y": 70,
                        "width": 760,
                        "height": 260,
                        "type": "image",
                    },
                    {
                        "name": "body",
                        "x": 20,
                        "y": 340,
                        "width": 760,
                        "height": 130,
                        "font_size_max": 18,
                        "font_size_min": 10,
                        "align": "left",
                        "bg_color": [0, 0, 0, 0],
                        "text_color": [0, 0, 0, 255],
                        "multiline": True,
                    },
                ],
                type_=JSONB(),
            )
        )
    )


def downgrade() -> None:
    """The squashed baseline is not reversible; drop and recreate the database."""

