"""cc_camera_marker_placement

Revision ID: 0016_marker_placement
Revises: 6dd44f55f21e
Create Date: 2026-07-20 10:50:09.231587

"""
from collections.abc import Sequence

import sqlalchemy as sa

import backend.core.time
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0016_marker_placement'
down_revision: str | Sequence[str] | None = '6dd44f55f21e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cts_cameras', sa.Column('marker_x_norm', sa.Float(), nullable=True))
    op.add_column('cts_cameras', sa.Column('marker_y_norm', sa.Float(), nullable=True))
    op.add_column('cts_cameras', sa.Column('marker_heading_deg', sa.Float(), nullable=True))
    op.add_column('cts_cameras', sa.Column('marker_set_at', backend.core.time.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cts_cameras', 'marker_set_at')
    op.drop_column('cts_cameras', 'marker_heading_deg')
    op.drop_column('cts_cameras', 'marker_y_norm')
    op.drop_column('cts_cameras', 'marker_x_norm')
    # ### end Alembic commands ###
