"""identity_continuity_m05_backfill_segments

Revision ID: 0017_backfill_segments
Revises: 0016_marker_placement
Create Date: 2026-07-20 18:35:23.845423

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0017_backfill_segments"
down_revision: str | Sequence[str] | None = "0016_marker_placement"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "presence_segments", sa.Column("backfill_revision_id", sa.String(length=64), nullable=True)
    )
    op.create_index(
        "uq_ps_backfill_revision_entered",
        "presence_segments",
        ["backfill_revision_id", "entered_at"],
        unique=True,
        postgresql_where=sa.text("backfill_revision_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_ps_backfill_revision_entered",
        table_name="presence_segments",
        postgresql_where=sa.text("backfill_revision_id IS NOT NULL"),
    )
    op.drop_column("presence_segments", "backfill_revision_id")
    # ### end Alembic commands ###
