"""Initial schema

Revision ID: 68d9e37c65c2
Revises:
Create Date: 2026-04-25 12:19:28.854209

"""
from collections.abc import Sequence

import sqlalchemy as sa

import backend.core.time
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68d9e37c65c2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cts_cameras',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rtsp_url', sa.String(length=1024), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('floor_plan_key', sa.String(length=512), nullable=True),
    sa.Column('homography', sa.JSON(), nullable=True),
    sa.Column('homography_residuals', sa.JSON(), nullable=True),
    sa.Column('privacy_zones', sa.JSON(), nullable=True),
    sa.Column('health_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cts_cameras_name'), 'cts_cameras', ['name'], unique=False)
    op.create_table('cts_dementia_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(length=255), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('window_start', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('window_end', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('acknowledged_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('received_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cts_dementia_signals_person_id'), 'cts_dementia_signals', ['person_id'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_severity'), 'cts_dementia_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_signal_type'), 'cts_dementia_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_window_end'), 'cts_dementia_signals', ['window_end'], unique=False)
    op.create_index(op.f('ix_cts_dementia_signals_window_start'), 'cts_dementia_signals', ['window_start'], unique=False)
    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('assistance_needed', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=256), nullable=True),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('media_paths_json', sa.JSON(), nullable=True),
    sa.Column('pipeline_data_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow_execution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_rule_name'), 'event_logs', ['rule_name'], unique=False)
    op.create_index('ix_event_logs_rule_status_ts', 'event_logs', ['rule_id', 'status', 'timestamp'], unique=False)
    op.create_index(op.f('ix_event_logs_status'), 'event_logs', ['status'], unique=False)
    op.create_index(op.f('ix_event_logs_timestamp'), 'event_logs', ['timestamp'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('font_filename', sa.String(length=256), nullable=False),
    sa.Column('regions_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_templates_name'), 'image_templates', ['name'], unique=True)
    op.create_table('media_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('presigned_url', sa.Text(), nullable=True),
    sa.Column('sensor_id', sa.String(length=128), nullable=True),
    sa.Column('captured_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_cache_captured_at'), 'media_cache', ['captured_at'], unique=False)
    op.create_index(op.f('ix_media_cache_expires_at'), 'media_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_media_cache_object_name'), 'media_cache', ['object_name'], unique=True)
    op.create_index(op.f('ix_media_cache_sensor_id'), 'media_cache', ['sensor_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ha_area_id', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=True),
    sa.Column('primary_sensor_id', sa.String(length=128), nullable=True),
    sa.Column('webhook_config', sa.JSON(), nullable=True),
    sa.Column('occupancy_config', sa.JSON(), nullable=True),
    sa.Column('telegram_trigger_config', sa.JSON(), nullable=True),
    sa.Column('cool_off_minutes', sa.Integer(), nullable=False),
    sa.Column('max_daily_triggers', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_executions', sa.Integer(), nullable=False),
    sa.Column('execution_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=True)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('event_log_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_data_json', sa.JSON(), nullable=False),
    sa.Column('started_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resume_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_step_id'], ['pipeline_steps.id'], ),
    sa.ForeignKeyConstraint(['event_log_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_rule_id'), 'workflow_executions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_table('active_image_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('expires_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_served_hash', sa.String(length=64), nullable=True),
    sa.Column('last_served_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['image_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_image_state_sensor_id'), 'active_image_state', ['sensor_id'], unique=True)
    op.create_table('activity_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('opened_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('closed_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('open_event_id', sa.Integer(), nullable=True),
    sa.Column('close_event_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['close_event_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['open_event_id'], ['event_logs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_sessions_activity_type'), 'activity_sessions', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_sessions_observation_id'), 'activity_sessions', ['observation_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_opened_at'), 'activity_sessions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_activity_sessions_person_id'), 'activity_sessions', ['person_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generated_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sleep_total_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('sleep_disruptions', sa.Integer(), nullable=True),
    sa.Column('meal_prep_count', sa.Integer(), nullable=True),
    sa.Column('meal_eating_count', sa.Integer(), nullable=True),
    sa.Column('meal_avg_duration_minutes', sa.Float(), nullable=True),
    sa.Column('medication_doses_taken', sa.Integer(), nullable=True),
    sa.Column('medication_doses_due', sa.Integer(), nullable=True),
    sa.Column('medication_adherence_pct', sa.Float(), nullable=True),
    sa.Column('bathroom_visit_count', sa.Integer(), nullable=True),
    sa.Column('bathroom_total_minutes', sa.Integer(), nullable=True),
    sa.Column('bathroom_avg_duration_minutes', sa.Float(), nullable=True),
    sa.Column('door_open_count', sa.Integer(), nullable=True),
    sa.Column('door_close_count', sa.Integer(), nullable=True),
    sa.Column('exercise_session_count', sa.Integer(), nullable=True),
    sa.Column('exercise_total_minutes', sa.Integer(), nullable=True),
    sa.Column('room_time_json', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.String(length=4096), nullable=True),
    sa.Column('summary_created_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('wellness_score', sa.Float(), nullable=True),
    sa.Column('wellness_alerts_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'report_date', name='uix_person_date')
    )
    op.create_index(op.f('ix_daily_reports_person_id'), 'daily_reports', ['person_id'], unique=False)
    op.create_table('person_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('detected_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['event_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_activities_activity_type'), 'person_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_person_activities_detected_at'), 'person_activities', ['detected_at'], unique=False)
    op.create_index(op.f('ix_person_activities_observation_id'), 'person_activities', ['observation_id'], unique=False)
    op.create_index(op.f('ix_person_activities_person_id'), 'person_activities', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_activities_session_id'), 'person_activities', ['session_id'], unique=False)
    op.create_table('person_location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('entered_at', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('exited_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('direction_semantic', sa.String(length=32), nullable=True),
    sa.Column('from_room_id', sa.Integer(), nullable=True),
    sa.Column('from_room_name', sa.String(length=128), nullable=True),
    sa.Column('superseded_by_revision_id', sa.String(length=64), nullable=True),
    sa.Column('global_track_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_location_history_entered_at'), 'person_location_history', ['entered_at'], unique=False)
    op.create_index(op.f('ix_person_location_history_global_track_id'), 'person_location_history', ['global_track_id'], unique=False)
    op.create_index(op.f('ix_person_location_history_person_id'), 'person_location_history', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_location_history_superseded_by_revision_id'), 'person_location_history', ['superseded_by_revision_id'], unique=False)
    op.create_table('person_location_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('current_room_id', sa.Integer(), nullable=True),
    sa.Column('current_room_name', sa.String(length=128), nullable=True),
    sa.Column('last_seen_at', backend.core.time.UTCDateTime(), nullable=True),
    sa.Column('last_sensor_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_location_state_person_id'), 'person_location_state', ['person_id'], unique=True)
    op.create_table('person_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_sightings_person_id'), 'person_sightings', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_sightings_sensor_id'), 'person_sightings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_person_sightings_timestamp'), 'person_sightings', ['timestamp'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_step_on_true', sa.Integer(), nullable=True),
    sa.Column('next_step_on_false', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_step_on_false'], ['pipeline_steps.id'], ),
    sa.ForeignKeyConstraint(['next_step_on_true'], ['pipeline_steps.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_rule_id'), 'pipeline_steps', ['rule_id'], unique=False)
    op.create_table('rule_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('negate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependent_rule_id', sa.Integer(), nullable=False),
    sa.Column('parent_rule_id', sa.Integer(), nullable=False),
    sa.Column('lookback_minutes', sa.Integer(), nullable=False),
    sa.Column('require_success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dependent_rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ha_entity_id', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_name'), 'sensors', ['name'], unique=False)
    op.create_table('interactive_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('timestamp', backend.core.time.UTCDateTime(), nullable=False),
    sa.Column('raw_response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.core.time.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactive_responses_created_at'), 'interactive_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactive_responses_execution_id'), 'interactive_responses', ['execution_id'], unique=False)
    op.create_index('ix_interactive_responses_execution_step', 'interactive_responses', ['execution_id', 'step_id'], unique=True)
    op.create_index(op.f('ix_interactive_responses_step_id'), 'interactive_responses', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactive_responses_step_id'), table_name='interactive_responses')
    op.drop_index('ix_interactive_responses_execution_step', table_name='interactive_responses')
    op.drop_index(op.f('ix_interactive_responses_execution_id'), table_name='interactive_responses')
    op.drop_index(op.f('ix_interactive_responses_created_at'), table_name='interactive_responses')
    op.drop_table('interactive_responses')
    op.drop_index(op.f('ix_sensors_name'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_table('rule_dependencies')
    op.drop_table('rule_contexts')
    op.drop_index(op.f('ix_pipeline_steps_rule_id'), table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_person_sightings_timestamp'), table_name='person_sightings')
    op.drop_index(op.f('ix_person_sightings_sensor_id'), table_name='person_sightings')
    op.drop_index(op.f('ix_person_sightings_person_id'), table_name='person_sightings')
    op.drop_table('person_sightings')
    op.drop_index(op.f('ix_person_location_state_person_id'), table_name='person_location_state')
    op.drop_table('person_location_state')
    op.drop_index(op.f('ix_person_location_history_superseded_by_revision_id'), table_name='person_location_history')
    op.drop_index(op.f('ix_person_location_history_person_id'), table_name='person_location_history')
    op.drop_index(op.f('ix_person_location_history_global_track_id'), table_name='person_location_history')
    op.drop_index(op.f('ix_person_location_history_entered_at'), table_name='person_location_history')
    op.drop_table('person_location_history')
    op.drop_index(op.f('ix_person_activities_session_id'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_person_id'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_observation_id'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_detected_at'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_activity_type'), table_name='person_activities')
    op.drop_table('person_activities')
    op.drop_index(op.f('ix_daily_reports_person_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_activity_sessions_person_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_opened_at'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_observation_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_activity_type'), table_name='activity_sessions')
    op.drop_table('activity_sessions')
    op.drop_index(op.f('ix_active_image_state_sensor_id'), table_name='active_image_state')
    op.drop_table('active_image_state')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_rule_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_media_cache_sensor_id'), table_name='media_cache')
    op.drop_index(op.f('ix_media_cache_object_name'), table_name='media_cache')
    op.drop_index(op.f('ix_media_cache_expires_at'), table_name='media_cache')
    op.drop_index(op.f('ix_media_cache_captured_at'), table_name='media_cache')
    op.drop_table('media_cache')
    op.drop_index(op.f('ix_image_templates_name'), table_name='image_templates')
    op.drop_table('image_templates')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_event_logs_timestamp'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_status'), table_name='event_logs')
    op.drop_index('ix_event_logs_rule_status_ts', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_rule_name'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_cts_dementia_signals_window_start'), table_name='cts_dementia_signals')
    op.drop_index(op.f('ix_cts_dementia_signals_window_end'), table_name='cts_dementia_signals')
    op.drop_index(op.f('ix_cts_dementia_signals_signal_type'), table_name='cts_dementia_signals')
    op.drop_index(op.f('ix_cts_dementia_signals_severity'), table_name='cts_dementia_signals')
    op.drop_index(op.f('ix_cts_dementia_signals_person_id'), table_name='cts_dementia_signals')
    op.drop_table('cts_dementia_signals')
    op.drop_index(op.f('ix_cts_cameras_name'), table_name='cts_cameras')
    op.drop_table('cts_cameras')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
